   services:
     app:
       build: .
       ports:
         - "3000:3000"
       environment:
         - PORT=3000
         - MERCADOPAGO_ACCESS_TOKEN=${MERCADOPAGO_ACCESS_TOKEN}
         - MERCADOPAGO_CLIENT_ID=${MERCADOPAGO_CLIENT_ID}
         - MERCADOPAGO_CLIENT_SECRET=${MERCADOPAGO_CLIENT_SECRET}
         - MERCADOPAGO_REDIRECT_URI=${MERCADOPAGO_REDIRECT_URI}
         - BACKEND_URL=${BACKEND_URL}
         - SUPABASE_URL=${SUPABASE_URL}
         - SUPABASE_KEY=${SUPABASE_KEY}
       volumes:
         - .:/usr/src/app
         - /usr/src/app/node_modules
         - /usr/src/app/dist